### ISSUE TITLE
Set up Heroku

### ISSUE THREAD

**Issue by gabichuelas** [HireUp-Turing/HireUp_backend#15]

**Comment by rrabinovitch** [comment]
Followed [this](https://github.com/iandouglas/flask-restful-travis-heroku#heroku-procfile) procfile example and followed [this](https://devcenter.heroku.com/articles/getting-started-with-python#deploy-the-app) deployment process (minus `heroku ps:scale web=1` which wasn't working, but didn't seem to hinder deployment)
