### ISSUE TITLE
Database structure options

### ISSUE THREAD

**Issue by rrabinovitch** [HireUp-Turing/HireUp_backend#4]
What do people use to build sites with extensive filtering?
e.g, MongoDB can store arrays

**Comment by gabichuelas** [comment]
Some notes:

**MongoDB**
- Document based (NoSQL)
- Can take arrays as a column attribute
    - For Node.js, you can reference an array of objects using Mongoose
- PyMongo is the driver to use MongoDB with Python
- Tables are called “Collections”
- Resources are called “Documents”
- Works with a JSON interface
- Great for scaling
- Great choice for managing customer analytics and product catalogs
- [Intro to MongoDB and Python](https://realpython.com/introduction-to-mongodb-and-python/)
- [How Document DBs Work](https://medium.com/astrolabs/understanding-how-document-databases-work-26085aa31629)

**Redis**
- “If an API is UX for programmers, then Redis should be in the Museum of Modern Art alongside the Mac Cube.”
- For python, use redis-py 
- Written in C
- Excellent choice for caching
- Steeper learning curve 
- works well when you know exactly what you need from the beginning (so, not us)

**Final Thoughts**
- although I still want to learn about MongoDB and it seems like it would be a good use case, doesn't sound like there are enough reasons to go with this over just a joins table between a `user` and `values` as well as `users` and `skills` for example.
- Might actually be a bad idea to try _both_ getting up to speed with Python/Django _and_ a new DB, like @rrabinovitch said
- "start small"
