### ISSUE TITLE
Django ORM

### ISSUE THREAD

**Issue by rrabinovitch** [HireUp-Turing/HireUp_backend#5]

**Comment by gabichuelas** [comment]
@rrabinovitch Django comes with a default ORM... it's just referred to as `Django ORM`..

- general Python ORM [article](https://www.fullstackpython.com/object-relational-mappers-orms.html)

_Interesting Tangents:_
[Orator](https://orator-orm.com/) - "an activerecord ORM for python"

**Comment by gabichuelas** [comment]
@rrabinovitch closing this out since we are choosing Flask. Will be in DONE column so we can still use resource links :)
