### ISSUE TITLE
General Django exploration

### ISSUE THREAD

**Issue by rrabinovitch** [HireUp-Turing/HireUp_backend#6]
explore tutorials, comparisons to the structure of Ruby apps, and other high level info that would be helpful to know about the framework

share helpful resources that you come across in your research in comments on this issue

**Comment by gabichuelas** [comment]
- [Quick/Superficial Rails to Django intro](https://medium.com/@carlosalmonte04/intro-to-django-for-rails-developers-1866dabe82c3)
- [Intro Tutorial](https://docs.djangoproject.com/en/2.0/intro/tutorial01/) to set up django project

**Comment by rrabinovitch** [comment]
[Python environment set up](https://opensource.com/article/19/5/python-3-default-mac) from Gaby

**Comment by gabichuelas** [comment]
Little Python [cheatsheet](https://pythonforhumans.com/notes/python-for-rubyists)

**Comment by rrabinovitch** [comment]
How I set up my environment:
* followed instructions in [python and package manager installation](https://github.com/pyenv/pyenv#installation) guide
* django
  * follow instructions for [virtual environment setup and launch](https://docs.python.org/3/tutorial/venv.html)
  * `pip install --upgrade pip` for version 20.2.4
  * [Installing an official release with pip](https://docs.djangoproject.com/en/3.1/topics/install/#installing-an-official-release-with-pip) - stop before "Installing a distribution-specific package" section
  * run `python` and then follow the instructions in the ["verifying" section](https://docs.djangoproject.com/en/3.1/intro/install/#verifying)
    * to exit this python interface (idk what to call it), hit `ctrl + d`
* to create django app
  *`django-admin startproject <app name>` (creates admin site??)
  * `cd <app name`
  * launch server: `python manage.py runserver`
  * create app: `python manage.py startapp <app name>`


come back to:
* https://docs.djangoproject.com/en/3.1/topics/install/#database-installation

questions:
* re: virtual environment - I'm unclear on whether i should be running this generally when developing in python/django or when it should come into play, if at all
* whats the diff bw the roles of `django-admin startproject <app name>` vs `python manage.py startapp <app name>`? (mysite vs polls in the [tutorial](https://docs.djangoproject.com/en/3.1/intro/tutorial01/))
* so routes/paths defined in `urls.py` don't specify what request verb is being used?

final versions:
* Python 3.7.3 (check with `python -V`)
* Django 3.1.2 (check with `python -m django --version`)

**Comment by rrabinovitch** [comment]
> * [Quick/Superficial Rails to Django intro](https://medium.com/@carlosalmonte04/intro-to-django-for-rails-developers-1866dabe82c3)
> * [Intro Tutorial](https://docs.djangoproject.com/en/2.0/intro/tutorial01/) to set up django project

@gabichuelas not sure how much this matters, but the django tutorial you linked above is for an older version - [this](https://docs.djangoproject.com/en/3.1/intro/tutorial01/) documentation seems to be updated. just want to make sure we're using the same versions across both our machines and setups

**Comment by gabichuelas** [comment]
@rrabinovitch  closing this out since we are choosing Flask. Will be in DONE column so we can still use resource links :)
